###############################################################################
# Application options
NFC_DEBUG_ENABLED=0
NFA_STORAGE="/data/nfc"
OFF_HOST_ESE_PIPE_ID=0x5E
OFF_HOST_SIM_PIPE_ID=0x0A
DEFAULT_OFFHOST_ROUTE=0xC0
DEFAULT_NFC_CLK_SRC=0x00
DEFAULT_SYS_CLK=0x00
HOST_LISTEN_TECH_MASK=0x07
OFFHOST_LISTEN_TECH_MASK=0x07
POLLING_TECH_MASK=0xEF
P2P_LISTEN_TECH_MASK=0x00
UICC_LISTEN_TECH_MASK=0x07
ISO_DEP_MAX_TRANSCEIVE=0xFEFF
AID_FOR_EMPTY_SELECT={08:A0:00:00:01:51:00:00}
DEFAULT_ISODEP_ROUTE=0x00
