###############################################################################
# NXP NFC Driver Configuration for OnePlus 11R (NXP SN100/SN110)
NXPLOG_GLOBAL_LOGLEVEL=0x03
NXPLOG_EXTNS_LOGLEVEL=0x03
NXPLOG_NCIHAL_LOGLEVEL=0x03
NXPLOG_NCIX_LOGLEVEL=0x03
NXPLOG_NCIR_LOGLEVEL=0x03
NXPLOG_FWDNLD_LOGLEVEL=0x03
NXPLOG_TML_LOGLEVEL=0x03

NXP_NFC_DEV_NODE="/dev/nq-nfc"
NXP_FW_NAME="libpn557_fw.so"
NXP_SYS_CLK_FREQ_SEL=0x00
NXP_SYS_CLOCK_TO_CFG=0x01
NXP_CLOCK_REQ_BY_FREQ=0x01
NXP_DEFAULT_SE=0x02
NXP_ENABLE_ADD_CHIP_RESET=0x01
NXP_ENABLE_ADD_FW_DOWNLOAD_RESET=0x01
NXP_ESE_POWER_DH_CONTROL=0x01
