NTP_SERVER=pool.ntp.org
AGPS_CONFIG_INJECT=1
DEFAULT_AGPS_ENABLE=TRUE
SUPL_HOST=supl.google.com
SUPL_PORT=7275
SUPL_MODE=1
SUPL_ES=1
LPP_PROFILE=3
INTERMEDIATE_POS=0
ACCURACY_THRES=5000
REPORT_POSITION_MODES=0
ENABLE_WIPER=0
CAPABILITIES=0x37
